file_categories = {
    "01 - m1_half_shaft_speed_no_mechanical_load": "Normal operation",
    "02 - m1_load_0.5Nm_half_speed": "Normal operation with load",
    "03 - m1_mechanically_imbalanced_half_speed": "Mechanical fault (shaft misalignment)",
    "03 - m1_mechanically_umbalanced_half_speed": "Mechanical fault (shaft misalignment)",
    "04 - m1_mechanically_imbalanced_half_speed": "Mechanical fault (shaft misalignment)", 
    "04 - m1_mechanically_umbalanced_half_speed": "Mechanical fault (shaft misalignment)",
    "05 - m1_mechanically_imbalanced_load_0.5Nm_half_speed": "Mechanical fault (shaft misalignment) with load",
    "05 - m1_mechanically_umbalanced_load_0.5Nm_half_speed": "Mechanical fault (shaft misalignment) with load",
    "06 - m1_electrically_50_ohm_fault_half_speed": "Electrical fault",
    "07 - m1_electrically_100_ohm_fault_half_speed": "Electrical fault",
    "08 - m1_electrically_150_ohm_fault_half_speed": "Electrical fault",
    "09 - m1_electrically_50_ohm_fault_load_0.5Nm_half_speed": "Electrical fault with load",
    "10 - m1_electrically_100_ohm_fault_load_0.5Nm_half_speed": "Electrical fault with load",
    "11 - m1_mechanically_imbalanced_electrically_50_ohm_fault_half_speed": "Mechanical and Electrical fault",
    "12 - m1_mechanically_imbalanced_electrically_100_ohm_fault_half_speed": "Mechanical and Electrical fault",
    "13 - m1_mechanically_imbalanced_electrically_150_ohm_fault_half_speed": "Mechanical and Electrical fault",
    "14 - m1_mechanically_imbalanced_electrically_50_ohm_fault_load_0.5Nm_half_speed": "Mechanical and Electrical fault",
    "15 - m1_with_m2_mechanicaly_imbalanced_on_background_half_speed": "Normal operation with noise",
    "15 - m1_with_m2_mechanicaly_umbalanced_on_background_half_speed": "Normal operation with noise",
    "16 - m1_mechanically_imbalanced_with_m2_normal_on_background_half_speed": "Mechanical fault with noise",
    "17 - m1_mechanically_imbalanced_with_m2_mechanicaly_imbalanced_on_background_half_speed": "Mechanical fault with high noise",
    "18 - m1_load_0.5Nm_m2_mechanically_imbalanced_on_background_half_speed": "Normal operation with load and noise",
    "19 - m1_mechanically_imbalanced_load_0.5Nm_m2_mechanically_imbalanced_on_background_half_speed": "Mechanical fault with load and noise",
    "20 - m1_electrically_50_ohm_fault_m2_imbalanced_on_background_half_speed": "Electrical fault with noise",
    "21 - m1_electrically_50_ohm_fault_load_0.5Nm_m2_mechanically_imbalanced_half_speed": "Electrical fault with load and noise",
    "22 - m1_electrically_100_ohm_fault_m2_mechanically_imbalanced_half_speed": "Electrical fault with noise",
    "23 - m1_electrically_100_ohm_fault_load_0.5Nm_m2_mechanically_imbalanced_half_speed": "Electrical fault with load and noise",
    "24 - m1_electrically_150_ohm_fault_m2_imbalanced_on_background_half_speed": "Electrical fault with noise",
    "25 - m1_mechanically_imbalanced_electrically_50_ohm_fault_m2_imbalanced_on_background_half_speed": "Mechanical and Electrical fault with noise",
    "26 - m1_mechanically_umbalanced_electrically_50_ohm_fault_load_0.5Nm_m2_umbalanced_on_background_half_speed": "Mechanical and Electrical fault with load and noise",
    "27 - m1_mechanically_imbalanced_electrically_100_ohm_fault_m2_imbalanced_on_background_half_speed": "Mechanical and Electrical fault with noise",
    "28 - m1_mechanically_imbalanced_electrically_100_ohm_fault_load_0.5Nm_m2_imbalanced_on_background_half_speed": "Mechanical and Electrical fault with load and noise",
    "29 - m1_mechanically_imbalanced_electrically_150_ohm_fault_m2_imbalanced_on_background_half_speed": "Mechanical and Electrical fault with noise",
    "30 - m1_mechanically_imbalanced_electrically_150_ohm_fault_m2_imbalanced_on_background_rotated_half_speed": "Mechanical and Electrical fault with noise"
}